spring:
  application:
    name: yu-ai-mother-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_ai_code_mother?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  profiles:
    active: local
server:
  servlet:
    context-path: /api
  port: 8123

  # springdoc-openapi????
  springdoc:
    group-configs:
      - group: 'default'
        paths-to-match: '/**'
        packages-to-scan: com.yupi.yuaicodemother.controller
  # knife4j???????????????
  knife4j:
    enable: true
    setting:
      language: zh_cn
# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-037de06ef27b4ebfaaa1cb33f455cdca
      model-name: deepseek-chat
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-037de06ef27b4ebfaaa1cb33f455cdca
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true
